### ISSUE TITLE
kat_plot_density: NameError: name 'colormaps' is not defined

### ISSUE THREAD

**Issue by mmokrejs** [TGAC/KAT#101]
```
$ kat_plot_density assembly_vs_assembly-main.mx
Traceback (most recent call last):
  File "/apps/gentoo/usr/lib/python-exec/python3.6/kat_plot_density", line 11, in <module>
    load_entry_point('kat==2.4.1', 'console_scripts', 'kat_plot_density')()
  File "/apps/gentoo/usr/lib64/python3.6/site-packages/kat/plot/density.py", line 167, in main
    pcol = plt.pcolormesh(matrix, vmin=0, vmax=zmax, cmap=colormaps.viridis,
NameError: name 'colormaps' is not defined
```

Is this a matplolib module?

[assembly_vs_assembly-main.mx.gz](https://github.com/TGAC/KAT/files/1961996/assembly_vs_assembly-main.mx.gz)

**Comment by maplesond** [comment]
Actually, this file comes with KAT.  I think this one is a bug when running directly from the python script.  I'll work on a fix for this one.  To workaround, it should be fine if run through kat itself.

**Comment by maplesond** [comment]
Hopefully, d8ecf78b730b3521deeacf5df90742a210fdb55f, should fix this one.

**Comment by mmokrejs** [comment]
See the assembly_vs_assembly-main.mx.gz above ready for testing.

**Comment by mmokrejs** [comment]
And would it be better to rename the colormaps module to something unique? Sounds like one could run into namespace collision once.

**Comment by maplesond** [comment]
It's probably fine, but just in case: d6dd0e2605ec176938d6fab5200cbc9840f0feb4

**Comment by mmokrejs** [comment]
Great, thank you.
