### ISSUE TITLE
Install KAT from source to user home directory

### ISSUE THREAD

**Issue by pbravakos** [TGAC/KAT#107]
I am trying to install KAT to my home directory on a server. My home directory /home/username is actually a link to /mnt/homes/username. When i am trying to run ./kat i get the following error:
[kat::FileSystemError*] = Could not find suitable directory containing KAT scripts at the expected location: /mnt/home/username. 

For a reason it confuses the /mnt/homes/username and the /home/username home folders to create this hybrid /mnt/home/username.
I do not have sufficient technical knowledge to solve this problem, so if you can help me solve this problem it would be really nice.
Thanks

**Comment by maplesond** [comment]
I think I may have fixed this in the latest commit on the develop branch.  I'm assuming you cloned the repo from git, can you try switching to the develop branch by typing 'git checkout develop', then try re-configuring and re-building?

**Comment by pbravakos** [comment]
Yes i have cloned the repo from git, and followed your instructions but the issue still remains. If there is a fix in the future please let me know.
Thank you

**Comment by SvitlanaLukicheva** [comment]
Hello,

I have the same problem. I installed KAT in my home directory, let's call it /myhome/myname, I obtained the same error and the displayed directory is /myhome//myhome/myname. I get this error with the latest version of KAT.

**Comment by bjclavijo** [comment]
hi @pbravakos  and @SvitlanaLukicheva , you probably have solved this somehow, but if not, can you give it a go to actually make sure when you are in installing Kat you have your PWD to be in a real path rather than a symlink?

Let me know it this solves your issue.

Best,

bj

**Comment by SvitlanaLukicheva** [comment]
Hello bjclavijo, thank you for your response! I don't think I used a symlink when I tried the installation. I finally could install KAT using conda.

**Comment by bjclavijo** [comment]
good, I'll close this then.
