### ISSUE TITLE
Changes from V2.3.4 to V2.4.1?

### ISSUE THREAD

**Issue by arangrhie** [TGAC/KAT#112]
Hello,

I used kat V2.3.4 comp to generate the spectra-cn plots.
The command I used for the two plots bellow was:
kat comp -o $genome/kat_comp -t 32 -H 10000000000 -I 10000000000 -m 22 -h -O 'read1.fastq read2.fastq' $genome.fasta

The only difference was that I used gz files for V2.4.1.

What happened from  2.3.4 to 2.4.1? Should I try without the -O option?

From the log, I can see the total k-mers in the hash1 and hash2 remains the same.
Here is the log:
```
kat-2.3.4/bin/kat comp -o bCalAnn1_c/kat_comp -t 32 -H 10000000000 -I 10000000000 -m 22 -h -O 'R1.BC.fastq R2.BC.fastq' bCalAnn1_c.fasta
Kmer Analysis Toolkit (KAT) V2.3.4

Running KAT in COMP mode
------------------------

Input 1 is a sequence file.  Counting kmers for input 1 (R1.BC.fastq R2.BC.fastq) ... done.  Time taken: 766.8s

Input 2 is a sequence file.  Counting kmers for input 2 (bCalAnn1_c.fasta) ... done.  Time taken: 4711.4s

Comparing hashes ... done.  Time taken: 6685.3s

Merging results ... done.  Time taken: 6.4s

Saving results to disk ... done.  Time taken: 0.4s

Creating plot(s) ... done.  Time taken: 3.5s

K-mer statistics for: 
 - Hash 1: "R1.BC.fastq"
 - Hash 2: "bCalAnn1_c.fasta"

Total K-mers in: 
 - Hash 1: 42759229948
 - Hash 2: 1995285405

Distinct K-mers in:
 - Hash 1: 4716509131
 - Hash 2: 1061522486

Total K-mers only found in:
 - Hash 1: 7615675622
 - Hash 2: 24787337

Distinct K-mers only found in:
 - Hash 1: 3679411125
 - Hash 2: 24424480

Shared K-mers:
 - Total shared found in hash 1: 35143554326
 - Total shared found in hash 2: 1970498068
 - Distinct shared K-mers: 1037098006
```

```
kat comp -o bCalAnn1_c/kat_comp -t 32 -H 10000000000 -I 10000000000 -m 22 -h -O 'read-BC_1.fastq.gz read-BC_2.fastq.gz' bCalAnn1_c.fasta
Kmer Analysis Toolkit (KAT) V2.4.1

Running KAT in COMP mode
------------------------

Input 1 is a sequence file.  Counting kmers for input 1 (read-BC_1.fastq.gz read-BC_2.fastq.gz) ... done.  Time taken: 810.6s

Input 2 is a sequence file.  Counting kmers for input 2 (bCalAnn1_c.fasta) ... done.  Time taken: 43.2s

Total K-mers in: 
 - Hash 1: 42759229948
 - Hash 2: 1995285405

Distinct K-mers in:
 - Hash 1: 4716509131
 - Hash 2: 1070643119

Total K-mers only found in:
 - Hash 1: 23417235073
 - Hash 2: 24787337

Distinct K-mers only found in:
 - Hash 1: 4194014440
 - Hash 2: 24464943

Shared K-mers:
 - Total shared found in hash 1: 19341994875
 - Total shared found in hash 2: 984113519
 - Distinct shared K-mers: 522494691
```
I get less shared number of k-mers from hash1 and hash2 in the log.

Plotting results clearly shows the difference (The 0-counts):
<V2.3.4>
![kat_comp-main mx spectra-cn 2 3 4](https://user-images.githubusercontent.com/12814549/44563712-6bdfdc00-a72d-11e8-92a3-39184330c819.png)

<V2.4.1>
![kat_comp-main mx spectra-cn 2 4 1](https://user-images.githubusercontent.com/12814549/44563767-ad708700-a72d-11e8-8d39-f6c7cbdf71d2.png)

And I get a suspicious error message as following when plotting in V2.4.1:
```
Creating plots
--------------

Plotting K-mer frequency distributions for general spectra ... done.
Plotting K-mer frequency distributions for 0x ... done.
Plotting K-mer frequency distributions for 1x ... done.
Plotting K-mer frequency distributions for 2x ... done.
Plotting K-mer frequency distributions for 3x ... /data/Phillippy/tools/conda/envs/kat/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/data/Phillippy/tools/conda/envs/kat/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
```

I've installed V2.4.1 yesterday from bioconda.
Any suggestions?

Thanks,
Arang

**Comment by maplesond** [comment]
Sorry, I missed the part about the -O option.  Are you sure you want to use this?  If so the the results in V2.4.1 look more like what I'd expect.  The results in V2.3.4 look as though the -O option was not applied correctly for some reason.

**Comment by bjclavijo** [comment]
Yes, definitely the problem here is canonical counting, make sure you understand the option, and it seems like older versions of KAT were not applying correctly.
For assembly QC you DO NOT want to use -O, ever. (Assembled sequences can end up in any strand).

Best,

bj

**Comment by arangrhie** [comment]
Thanks, I had the same results without the -O option. So I guess this was an issue with the previous version not properl handling the -O. And yes, I wouldn't use the -O option again. Will close this issue.
