### ISSUE TITLE
Kat comp unable to read input fastq file

### ISSUE THREAD

**Issue by mrimis** [TGAC/KAT#118]
Hello,

I am running kat comp on my paired-end reads and reference assembly. It was able to count Khmer hashes for reference assembly. But it is unable to read my paired end reads. Here is the command which I entered - 
kat comp -t 8 -o pe_v_ref_test 'valid_R1.fastq.gz valid_R1.fastq.gz' BS_FINAL_from_draft.fasta

The error I am getting is this - 

src/input_handler.cc(103): Throw in function void kat::InputHandler::validateMerLen(uint16_t)
Dynamic exception type: boost::exception_detail::clone_impl<kat::JellyfishException>
std::exception::what: std::exception
[kat::JellyfishError*] = Cannot process hashes that were created with different K-mer lengths.  Expected: 27.  Key length was 0 for : valid_R1.fastq.gz
Sat Nov 17 10:36:20 EST 2018

**Comment by gonzalogacc** [comment]
Hi Mrimis.
You need to unzip the files or use process substitution.

`kat comp -t 8 -o pe_v_asm_test <(bzip2 -dc 'PE1.R?.fq.bz2') asm.fa`

Check here for more info
[Docs](https://kat.readthedocs.io/en/latest/using.html)

Best
Gonza.-

**Comment by mrimis** [comment]
Hi,

I ran successfully kat comp but it is taking lot of memory and it is saying job exceeded memory limit. Is it anyway to get around this issue
The command to run kat comp is - 
kat comp -t 25 -o pe_v_ref_genome 'L3_128_R?.fq L3_50_R?.fq L4_140_R?.fq L4_50_R?.fq L5_143_R?.fq L6_48_R?.fq L7_48_R?.fq L8_16_R?.fq L8_51_R?.fq' BS_FINAL_from_draft.fasta

The error I am getting is as follows-
Warslurmstepd: error: Job 28022334 exceeded memory limit (220601664 > 209715200), being killed
slurmstepd: error: Exceeded job memory limit
slurmstepd: error: *** JOB 28022334 ON c5a-s22 CANCELLED AT 2018-11-17T23:08:41 ***

**Comment by gonzalogacc** [comment]
Check issue #116 
Gonza.

**Comment by bjclavijo** [comment]
I think this is solved?
