### ISSUE TITLE
kat comp 

### ISSUE THREAD

**Issue by wul88** [TGAC/KAT#130]
kat comp failed when using multiple nodes in a cluster. The error is at the end of this note.

If I run it using one node with multiple CPUs, it finishes fine. The problem with our cluster setting is that the max memory with high memory node is 1TB. The actual useable memory is 950GB. I wondered if it is the kat comp program's limitation, or it is our PBS cluster scheduler configuration issue.  

+ kat comp -o o18pe_assemK71 -t 40 -m 71 -H 8000000000 -N -I 3600000000 -O /gpfs/scratch/lxw34/oCelTr24_1Pfastp.fa /gpfs/scratch/lxw34/oCelTr24_2Pfastp.fa ../oSOAP_preG.scafSeq
../deps/seqan-library-2.0.0/include/seqan/basic/basic_exception.h:368 FAILED!  (Uncaught exception of type std::runtime_error: Hash full)
../deps/seqan-library-2.0.0/include/seqan/basic/basic_exception.h:368 FAILED! /var/spool/torque/mom_priv/jobs/12815089.torque01.util.production.int.aci.ics.psu.edu.SC: line 34: 44793 Aborted                 (core dumped) kat comp -o o18pe_assemK71 -t 40 -m 71 -H 8000000000 -N -I 3600000000 -O $FINALDIR/oCelTr24_?Pfastp.fa ../oSOAP_preG.scafSeq

**Comment by maplesond** [comment]
Unfortunately, KAT doesn't use OpenMPI or some technology like that which would enable it to work across nodes.  In fact using KAT in this way would kill performance.  So the process is limited to a single node.  @bjclavijo might be able to help come up with workarounds to the problem.

**Comment by wul88** [comment]
Thank you for your swift answer. It is good to know the limitation. I am in the process in purchasing computation allocation and have experienced several software that shared the same limitation. Is there a way to work around it? 

If you could please include this information in the manual it shall help others.  Thanks!
