### ISSUE TITLE
Installation problem: libboost_timer.so.1.66.0

### ISSUE THREAD

**Issue by martynakgajos** [TGAC/KAT#131]
I haven't gotten any errors while installing KAT. 
However, with any kat command I get following error:
kat: error while loading shared libraries: libboost_timer.so.1.66.0: cannot open shared object file: No such file or directory
How can I solve it?

**Comment by andreirozanski** [comment]
Maybe check how LD_LIBRARY_PATH looks like.  For me, after pointing it to deps/boost/stage/lib it worked.

**Comment by hermannschwaerzlerUIBK** [comment]
Hi @martynakgajos,

this issue is quite old but maybe you are still interested. :-)
My way of solving this problem was adding an additional step after _./build_boost.sh_:

```
INSTALL_DIR=/usr/local   # or whichever installation directory you use
...
./build_boost.sh
(cd deps/boost/build/lib/ && tar cf - .) | ( cd $INSTALL_DIR/lib && tar xf -)
```
