### ISSUE TITLE
how to explain the shared distinct kmers so small compared to shared found in each individual hash? 

### ISSUE THREAD

**Issue by wul88** [TGAC/KAT#132]
I am using kat2.3.1.
I have a ~40x Illumina PE reads of a mammalian genome. The R1 vs. R2 kmer frequency matrix plot ONLY shows exclusive content curves. (see below) I am not sure how to interpret this phenomena. The Jaccard distance is so low that the two reads seemed not from the same sample, which does not make any sense. Could you please take a look and give some advice? Thanks much!

![image](https://user-images.githubusercontent.com/31707366/60349011-b99d2480-998e-11e9-8719-2550972efdf3.png)
 
commands I used to generate matrix file
kat comp -n -t 16 -o o18R1_R2 -m 71 -H 1000000000 -I 1000000000 \
 /gpfs/scratch/lxw34/oCelTr24_1Pfastp.fa /gpfs/scratch/lxw34/oCelTr24_2Pfastp.fa

The following is the stat data of R1 and R2

K-mer statistics   for:
--
-   Hash 1: "/gpfs/scratch/lxw34/oCelTr24_1Pfastp.fa"
-   Hash 2: "/gpfs/scratch/lxw34/oCelTr24_2Pfastp.fa"
 
Total K-mers in:
-   Hash 1: 30471283197
-   Hash 2: 28517083378
 
Distinct K-mers in:
-   Hash 1: 4095287000
-   Hash 2: 4043001755
 
Total K-mers only found in:
-   Hash 1: 1499746373
-   Hash 2: 1453659181
 
Distinct K-mers only found in:
-   Hash 1: 1422221809
-   Hash 2: 1369936564
 
Shared K-mers:
-   Total shared found in hash 1: 28971536824
-   Total shared found in hash 2: 27063424197
-   Distinct shared K-mers: 2673065191
 
Distance between spectra 1 and 2 (all   k-mers):
-   Manhattan distance: 3.09163e+08
-   Euclidean distance: 7.77242e+07
-   Cosine distance: 0.000958775
-   Canberra distance: 71.9626
-   Jaccard distance: 0.0731968
 
Distance between spectra 1 and 2 (shared   k-mers):
-   Manhattan distance: 2.64575e+08
-   Euclidean distance: 6.05709e+07
-   Cosine distance: 0.00362099
-   Canberra distance: 72.0153
-   Jaccard distance: 0.0943107

**Comment by gonzalogacc** [comment]
Hi, sorry for the delay.
That's just an axis range problem, y only goes to 1K. Replot the matrix adjusting the Y max parameter to a suitable number and the shared components should appear.
Best
Gonza.-
