### ISSUE TITLE
Is KAT comp 0 or 1-based indexing

### ISSUE THREAD

**Issue by malonge** [TGAC/KAT#133]
Hi there,

In the kat comp output matrix, does it use 0 or 1 based indexing? In other words, does the top left number (row=0, column=0) refer to the number of k-mers with 0 frequency in the the first and second k-mer sets? Or is it the number of k-mers with a frequency of 1 in the first and second k-mer sets?

Thank you

**Comment by bjclavijo** [comment]
It starts at 0, as it needs to show kmers that are exclusive to each set.

Best,

bj

**Comment by malonge** [comment]
That makes sense. Thanks for the quick response!
