### ISSUE TITLE
Failing to find installed python modules

### ISSUE THREAD

**Issue by krobison13** [TGAC/KAT#134]
I'm trying to build from source and make check is failing.  It appears that standard python3 modules (e.g. matplotlib) -- which ASFAIK are in standard locations --are failing to be found 

I tried "sudo apt-get install python3-dev" and that said nothing required updating.  

Any suggestions for troubleshooting (or how I could provide useful data) much appreciated.

**Comment by bjclavijo** [comment]
I guess, this is probaly solved already, but if not, try using a new env when building.
CLosing this due to its age.
