### ISSUE TITLE
Extracting sequences of kat comp  2x multiplicity kmers

### ISSUE THREAD

**Issue by MrKevinDC** [TGAC/KAT#135]
I was interested in a feature similar to this. I would like to be able to extract all the k-mer sequences that  have a 2x multiplicity according to the k-mer comparison plot of kat comp. Is there currently any way to do this?

I have tried making use of the .mx file and the jellyfish dumps but cant figure out how they are related.

_Originally posted by @MrKevinDC in https://github.com/TGAC/KAT/issues/75#issuecomment-533446418_

**Comment by gonzalogacc** [comment]
Hi Kevin
You need to dump the JF hash and then you can use the -U and -L parameters to slice the spectra.
Best
Gonza.-

**Comment by MrKevinDC** [comment]
Hi Gonza,

You mean run jellyfish dump on the .jf27 with the upper and lower k-mer counts right? I'm sorry to have to ask further, those count values are the ones in the distanalysis json?

Thank you again
