### ISSUE TITLE
interpreting the image of cold 

### ISSUE THREAD

**Issue by dcopetti** [TGAC/KAT#137]
Hi,
I am using KAT to assess the completeness of a long read WGS assembly.
I run KKAT comp and it looks OK:
![Rab1_flye191004_kat23-main mx spectra-cn_160](https://user-images.githubusercontent.com/13842014/69358671-83d34200-0c87-11ea-9112-f58fa68f5e8a.png)
I know there are parts missing and others collapsed.
Then I run KAT cold on the same files, and I get this:
![Rab1_flye191004_kat-cold](https://user-images.githubusercontent.com/13842014/69358740-a1a0a700-0c87-11ea-99cd-dda6e2533da1.png)
How should I interpret it? Looks like there are lots of contigs at high multiplicity (orange circles). Can the cloud on top left be indicative of a contamination (e.g. endophitic fungus in a plant sample)?
Thanks,
Dario

**Comment by gonzalogacc** [comment]
Hi Dario.
Please check the section 4.4 of the [walkthrough](https://kat.readthedocs.io/en/latest/walkthrough.html), where GCP plots are described.
The plots are slightly different but the idea is the same.
Best
Gonza.-

**Comment by dcopetti** [comment]
Hi @gonzalogacc ,

I wonder if you have time to address the issue #128 , where we can't run the distanalysis.py script.
For me it would be very useful to select the right peaks to get better stats on my genome and assembly.
Thanks!
Dario
