### ISSUE TITLE
Kat comp x-axis

### ISSUE THREAD

**Issue by vmixao** [TGAC/KAT#139]
Hello,

I have installed kat v2.4.1 with bioconda, and for some of the read libraries (not all), the kat comp output cuts the x-axis of the plot. I am attaching one of those situations, as an example. Other people from the lab, using kat v2.3.1 manage to get a proper plot, with the full x-axis. Can you please help solving this issue? Is there a way to define the x-axis?

Thanks in advance!

![kat-comp-main mx spectra-cn](https://user-images.githubusercontent.com/19263468/72451353-1261cc80-37bc-11ea-8ea2-0d4a228a76bb.png)

**Comment by jonwright99** [comment]
You should be able to replot with an extended x axis using the maxtrix file (.mx) generated from your first plot like so;

```
kat plot spectra-cn -x 200 -o <output_file> <matrix_file>
```

Try ```kat plot spectra-cn --help``` for other options

**Comment by vmixao** [comment]
Thanks! It works.

Best
Verónica
