### ISSUE TITLE
Error while loading shared libraries (libboost version trouble)

### ISSUE THREAD

**Issue by dgroso** [TGAC/KAT#145]
`kat: error while loading shared libraries: libboost_filesystem.so.1.60.0: cannot open shared object file: No such file or directory`

I get this error message when attempting to use kat for the first time via anaconda. I tried using `conda install -c anaconda boost=1.60` to try and downgrade version 1.67 (which is the default when Kat is installed), and this did not work. Any suggestions are appreciated.

**Comment by elfore** [comment]
@dgroso I am having the same issue when I install kat into an existing env. Creating an empty new env through conda solved this problem. With you good luck.
