### ISSUE TITLE
Linking error with RHEL8

### ISSUE THREAD

**Issue by eandersonIGS** [TGAC/KAT#146]
Hello,

I am in the process of rebuilding all our tools for our Institute's upgrade to RHEL8 from RHEL7. I can successfully build KAT v2.2.0 in our RHEL7 environment, but am running into an error during linking while building it under RHEL8.

`  CXX      sub_commands/cite_main.o
  CXX      sub_commands/mem_main.o
  CXX      jellyfish/merge_files.o
  CXX      lib/rectangular_binary_matrix.lo
  CXX      lib/mer_dna.lo
  CXX      lib/storage.lo
  CXX      lib/allocators_mmap.lo
  CXX      lib/misc.lo
  CXX      lib/int128.lo
  CXX      lib/thread_exec.lo
  CXX      lib/jsoncpp.lo
  CXX      lib/time.lo
  CXX      lib/generator_manager.lo
  CXXLD    libkat_jellyfish.la
  CXXLD    bin/kat_jellyfish
/usr/bin/ld: cannot find -lstdc++
collect2: error: ld returned 1 exit status
make[4]: *** [Makefile:1156: bin/kat_jellyfish] Error 1
make[4]: Leaving directory '/autofs/src/kat/kat-2.4.0/rhel8x86_64/KAT-master/deps/jellyfish-2.2.0'
make[3]: *** [Makefile:1867: all-recursive] Error 1
make[3]: Leaving directory '/autofs/src/kat/kat-2.4.0/rhel8x86_64/KAT-master/deps/jellyfish-2.2.0'
make[2]: *** [Makefile:901: all] Error 2
make[2]: Leaving directory '/autofs/src/kat/kat-2.4.0/rhel8x86_64/KAT-master/deps/jellyfish-2.2.0'
make[1]: *** [Makefile:475: all-recursive] Error 1
make[1]: Leaving directory '/autofs/src/kat/kat-2.4.0/rhel8x86_64/KAT-master'
make: *** [Makefile:399: all] Error 2`

I am not sure why ld can't find stdc++

`[eanderson@joja kat]$ locate stdc++|grep .so
/usr/lib/gcc/x86_64-redhat-linux/8/libstdc++.so
/usr/lib/gcc/x86_64-redhat-linux/8/32/libstdc++.so
/usr/lib64/libstdc++.so.6
/usr/lib64/libstdc++.so.6.0.25
/usr/share/gdb/auto-load/usr/lib64/libstdc++.so.6.0.25-gdb.py
/usr/share/gdb/auto-load/usr/lib64/__pycache__/libstdc++.so.6.0.25-gdb.cpython-36.opt-1.pyc
/usr/share/gdb/auto-load/usr/lib64/__pycache__/libstdc++.so.6.0.25-gdb.cpython-36.pyc`

I believe I have double checked that all the dependencies are installed but it's always possible that I missed something. I know 2.4.0 is not the latest release but we have people who are currently using that version and can't change versions mid-project. Do you have any ideas of something I can try?

Thank you

**Comment by bjclavijo** [comment]
Hi, I expect you will have sorted out this one already, but the only solution is to move to a newer version. If you still have problems compiling the latest version and all requirements are met, please let us know.
You should have no problem moving versions mid-project, since the format of intermediate tools and the behaviour of the tools has not changed.

Best,

bj
