### ISSUE TITLE
K-mer sequence of k-mer with specific frequency

### ISSUE THREAD

**Issue by dbau-igenomix** [TGAC/KAT#149]
Hi,

Is it possible to get the k-mer sequence associated with each k-mer frequency obtained with `kat hist`? For example:

```
# Title:9-mer spectra for: phiX.fasta
# XLabel:9-mer frequency
# YLabel:# distinct 9-mers
# Kmer value:9
# Input 1:phiX.fasta
###
1 4972
2 189
3 8
4 1
5 0
6 0
7 0
8 0
9 0
...
```

Would it be possible to the the sequence corresponding to the 9-mer with frequency 4?

Thanks,
Davide

**Comment by bjclavijo** [comment]
Hi Davide. I'm sure you've already sorted this one out, but in case you have not, jellyfish has that functionality.
