### ISSUE TITLE
auto-detect "-C"

### ISSUE THREAD

**Issue by thackl** [TGAC/KAT#15]
This really is nothing crucial, but I forget to set the flag properly again today, so it would help me coping with my stupidity.. It should be quite easy to parse that information, e.g. `jellyfish info HASH` contains  canonical: yes/no.

**Comment by maplesond** [comment]
Hi Thomas,

I'm not sure I understand.  This should already be detected from the hash header if working with existing hashes.  Obviously, if working with fastas or fastqs then you have to specify.  Are you saying that when loading hashes the canonical setting is incorrect?  If so then this is a bug and I'll need to investigate the code.

Thanks,
Dan

**Comment by thackl** [comment]
Currently, the help for `kat gcp` says:
```
  -C [ --canonical ]                      IMPORTANT: Whether the jellyfish hashes contains K-mers 
                                          produced for both strands.  If this is not set to the 
                                          same value as was produced during jellyfish counting then
                                          output will be unpredictable.
```

so I was always specifying manually / reran the runs I forgot to submit with `-C`. I'm using hashes directly. Maybe I just misunderstood the help.

**Comment by maplesond** [comment]
Ahh.  I think I didn't get around to updating the help messages.  So the behaviour is that this sets the canonical flag to determine how to populate the hash when counting fast(a/q) files.  For existing hashes the canonical flag should be extracted from the hash header.  I'll update the help so this is clearer.

Thanks again for pointing this out.

**Comment by thackl** [comment]
Ah, perfect. Thanks!

**Comment by maplesond** [comment]
Updated, the develop branch with new help messages.  Closing ticket.
