### ISSUE TITLE
Using KAT on metagenomics data

### ISSUE THREAD

**Issue by bistace** [TGAC/KAT#151]
Hi,

we have sequenced and assembled metagenomic samples using two different sequencing technologies and we would like to compare the results. 

I have already been using KAT extensively on isolated organisms (notably the spectra-cn function, which is very handy) but I was wondering if there was a best-practice way to compare the k-mers of both assemblies to k-mers in reads and if you had any experience on using KAT with metagenomics assemblies.

**Comment by bjclavijo** [comment]
This is very old, but to compare two different assemblies, use the same read set (normally your more precise/higher coverage one, usually illumina) and then simply produce spectra-cn for both and compare those.

Regarding using KAT for metagenomic data, it really depends on the dataset, it can be interesting, but it may be challenging. the tools will run, but the interpretation can be quite challenging.
