### ISSUE TITLE
configure error

### ISSUE THREAD

**Issue by annanikulina** [TGAC/KAT#16]
Hi,

I am trying to install KAT, but end up with the following error after running **./configure**:
`sh ./configure --with-boost=~/tools/boost_1_55_0/`

``` sh
.....
checking for boostlib >= 1.52... yes
checking whether the Boost::Filesystem library is available... yes
configure: WARNING: Could not find a dynamic version of the library!
configure: error: Could not find any version of the library to link to
```

Is it a problem with boost or something else?

Thanks!

**Comment by maplesond** [comment]
Hi,

It looks like KAT is unable to detect your boost libraries.  Is your boost installation compiled and working?  If so then there is probably some kind of unexpected file structure between the directory you pointed to.  This is quite often the case if installing in a HPC environment.  KAT will need to get to the ".so" and ".hpp" files, so you probably want to point to a directory above those (i.e. probably the directory containing the "include" and "lib" directories.)

**Comment by annanikulina** [comment]
It is indeed HPC and boost seems to be working.
Thanks for the suggestions, I ll try to figure it out.

**Comment by sjackman** [comment]
I also got this same error and was able to fix it by passing `--with-boost=/usr/local/Cellar/boost/1.60.0_1` on Homebrew. Gist log of the failed build:
https://gist.github.com/sjackman/47111b137d8b17bd5049ce13002eacef#file-01-configure-L101

**Comment by maplesond** [comment]
Did Shaun's suggestion help?  In any case, dependency detection should be improved in the latest version so hopefully there's no longer an issue here.  I'll close the case but feel free to reopen if there are any outstanding issues.

**Comment by sjackman** [comment]
@annanikulina You can try if you like using Linuxbrew to install kat. See http://linuxbrew.sh and then
`brew install homebrew/science/kat`

**Comment by brainstorm** [comment]
Yeah, same issue here but on Australian HPC, had to pass this to the cmdline:

```
./configure --with-boost=/usr/local/easybuild/software/Boost/1.61.0-intel-2017.u2-GCC-5.4.0-CUDA8-Python-3.5.2
```

**Comment by sjackman** [comment]
By coincidence just today I created a new formula for `kat` for both Linux and macOS.
```sh
brew install brewsci/bio/kat
```
See https://github.com/brewsci/homebrew-bio/blob/master/Formula/kat.rb
and https://brew.sh and http://linuxbrew.sh

**Comment by bjclavijo** [comment]
@maplesond do you think it may be a good idea to recommend brew as a nice way to get kat installed in the readme? I would put it on the first line of the installation instructions, with a huge thanks to @sjackman

**Comment by maplesond** [comment]
Hi @bjclavijo and @sjackman,

We can definitely include it as an installation option in the readme.  It would be good to create a new formula for the upcoming release.  The installation process will be slightly different... the main changes are including a boost subset in the git repo, and we no longer support the tarball distributions.  I'll have a look at the latest changes to the formula that @sjackman proposes above and adapt to the latest code.

**Comment by maplesond** [comment]
@sjackman and @bjclavijo, I've updated the documentation in the develop branch to reflect installation from brew.  

@sjackman for the upcoming versions the kat formula will need a couple of mods over an above the normal changes.  The installation procedure going forward will be something like "./build_boost && ./autogen.sh && ./configure [options] && make && make install".  This will be true whether pulled from head, or downloaded from a tagged release commit.  Many thanks for all your help getting the latest formula together!

**Comment by sjackman** [comment]
A PR to `brewsci/bio/kat` with the updated release would be much appreciated!

With vendoring Boost into KAT, are the resulting KAT executables dynamically linked to any Boost libraries?

**Comment by sjackman** [comment]
Cool. That's what I was checking. Thanks, Daniel.
