### ISSUE TITLE
GC content plot Z and X axis labels switched. 

### ISSUE THREAD

**Issue by mahesh-panchal** [TGAC/KAT#17]
I noticed on K-mer coverage vs GC count plot, that the labels for Z and X are switched. X has the label # Distinct K-mers, and Z is k-mer multiplicity

**Comment by maplesond** [comment]
As with ticket #18, this is something that will be fixed in the next release.  In the meantime, try pulling from the current head of the develop branch (a8f3557) to see if that works for you.
