### ISSUE TITLE
Kat plot density x, y, and z parameters are not working.

### ISSUE THREAD

**Issue by mahesh-panchal** [TGAC/KAT#18]
I'm using KAT/2.0.6 and trying to change the x y and z axis maximums is not working. It produces the default x,y,z=1000.

**Comment by maplesond** [comment]
Thanks for letting me know.  I've already been looking into a fix for this and will be addressed in the next release.  If you need an immediate fix, you can try pulling from the current head of the develop branch (a8f3557c443827541e54d923ac07330c66a0ab5c) to see if that works for you?
