### ISSUE TITLE
configure problem

### ISSUE THREAD

**Issue by chjp** [TGAC/KAT#19]
configure.ac:42: error: possibly undefined macro: AM_PROG_AR
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/bin/autoconf failed with exit status: 1

**Comment by maplesond** [comment]
Thanks for pointing this out.  I'll look into fixing this for the next release.

**Comment by maplesond** [comment]
I've added the change to the configure.ac file in the develop branch.  The change will be present in V2.1 as soon as that's released.  I'll leave this case open until that time.

**Comment by maplesond** [comment]
Should be fixed in the latest release: https://github.com/TGAC/KAT/releases/tag/Release-2.1.0.  Please reopen if there are any issues.
