### ISSUE TITLE
Sometimes hash doubling does not work. 

### ISSUE THREAD

**Issue by mahesh-panchal** [TGAC/KAT#21]
Warning: Specified hash size insufficent - attempting to double hash size...
Warning: Specified hash size insufficent - attempting to double hash size...
Warning: Specified hash size insufficent - attempting to double hash size...
Warning: Specified hash size insufficent - attempting to double hash size...
Warning: Specified hash size insufficent - attempting to double hash size...
Warning: Specified hash size insufficent - attempting to double hash size...
Warning: Specified hash size insufficent - attempting to double hash size...
Warning: Specified hash size insufficent - attempting to double hash size...
Warning: Specified hash size insufficent - attempting to double hash size...
Warning: Specified hash size insufficent - attempting to double hash size...
Warning: Specified hash size insufficent - attempting to double hash size...
Warning: Specified hash size insufficent - attempting to double hash size...
Warning: Specified hash size insufficent - attempting to double hash size...
Warning: Specified hash size insufficent - attempting to double hash size...
Warning: Specified hash size insufficent - attempting to double hash size...
Warning: Specified hash size insufficent - attempting to double hash size...../deps/seqan-library-2.0.0/include/seqan/basic/basic_exception.h:368 FAILED!  (Uncaught exception of type std::runtime_error: Hash full../deps/seqan-library-2.0.0/include/seqan/basic/basic_exception.h:368 FAILED!  (Uncaught exception of type std::runtime_error: Hash full)
../deps/seqan-library-2.0.0/include/seqan/basic/basic_exception.h:368 FAILED!  (Uncaught exception of type std::runtime_error: Hash full)
../deps/seqan-library-2.0.0/include/seqan/basic/basic_exception.h/var/spool/slurmd/job6484335/slurm_script: line 44: 19879 Aborted                 (core dumped) kat comp -p -t 16 -C -D -o unfiltered141121_BC5DJLANXXread1_vs_read2 $READFWD $READREV

It worked on the two files before, but then crashed on the third. I'm not sure what causes this.

**Comment by maplesond** [comment]
It's generally best to try and specify a sufficiently large hash size prior to running KAT, as increasing the hash size on the fly will dramatically slow the tool down.  Having said that, the code shouldn't fail.  Before I investigate further could you verify that you are not simply running out of memory on your system?

**Comment by mahesh-panchal** [comment]
The job would be killed by the submission manager with a message if I 
exceeded memory. It's definitely not that.

**Comment by maplesond** [comment]
Hi Mahesh,

Sorry for the delay in getting back to you.  Can you work around this by setting the hash size to an appropriate number up front?  I haven't been able to reproduce on my system, so could you provide the input files and command lines that are causing the problem?

Thanks,
Dan

**Comment by mahesh-panchal** [comment]
Hi Dan,

I think this might be something to do with the infrastructure here. I 
must admit, I don't remember which of my many samples that I generated 
that error on. For the one I think it's on, it seems to have run through 
fine a second time (or third or fourth -- too many things going haywire 
recently).

Since KAT is part of our general assembly pipeline, and for some of the 
samples given to me I don't know genome size, it's hard to estimate a 
good hash size off the bat.

I guess for now this will be unresolved. I'll try to make sure I can 
replicate the error if I see it again.

Regards,
Mahesh.

**Comment by maplesond** [comment]
Ok, just let me know if you manage to reproduce.  

Good to know KAT's integrated into your assembly pipeline! Nice to see it being used in production environments. :)

**Comment by maplesond** [comment]
Hi Mahesh, have you managed to reproduce the issue?  

I'll close this issue for now, but please reopen if you encounter the problem again.
