### ISSUE TITLE
Symlink to fasta read in as hash

### ISSUE THREAD

**Issue by mahesh-panchal** [TGAC/KAT#24]
Hi Dan,

I think the issue here is my file which is a symlink to a symlink of a fasta file is being read in as a jellyfish hash. (I'm not certain is the cause, but it's the most likely I came up with given the error)

Error output:
/pica/v3/b2011228_nobackup/Debaryomyces_automated/04_Validation/P1260_1001/P1260_1001_soapdenovo_67_assembly.fasta exists or is linked correctly
Kmer Analysis Toolkit (KAT) V2.0.6

Running KAT in COMP mode
------------------------

Input is a sequence file.  Counting kmers for Allreads.fastq ... done.  Time taken: 15.1s

KAT COMP completed.
Total runtime: 15.2s

input_handler.cc(94): Throw in function void kat::InputHandler::validateMerLen(uint16_t)
Dynamic exception type: boost::exception_detail::clone_impl<kat::JellyfishException>
std::exception::what: std::exception
[kat::JellyfishError*] = Cannot process hashes that were created with different K-mer lengths.  Expected: 27.  Key length was 0 for : /pica/v3/b2011228_nobackup/Debaryomyces_automated/04_Validation/P1260_1001/P1260_1001_soapdenovo_67_assembly.fasta

Regards,
Mahesh.

**Comment by maplesond** [comment]
Hi Mahesh,

Does it work if you use the canonical path to the file (i.e. absolute path after all dereferencing has occurred)?  If so I'll check the code.  I make extensive using of the boost libraries file handling code, and this seems to treat real files and symlinks differently, so there maybe a potential issue.

Dan

**Comment by mahesh-panchal** [comment]
Hi Dan,

I used readlink -f to replace the symlink with the cannonical name. It 
still crashed, but I realised that the file ending wasn't fasta either 
(although it is a fasta file).

/proj/b2011228/nobackup/Debaryomyces_automated/04_Validation/P1260_1001/P1260_1001_soapdenovo_67_assembly.fasta 
exists or is linked correctly
Canonical path: 
/pica/v3/b2011228_nobackup/Debaryomyces_automated/03_Assembly/P1260_1001/soapdenovo_67_assembly/soapdenovo_67_assembly_graph.scafSeq
Kmer Analysis Toolkit (KAT) V2.0.6

Running KAT in COMP mode
------------------------

Input is a sequence file.  Counting kmers for Allreads.fastq ... done. 
Time taken: 14.9s

KAT COMP completed.
Total runtime: 14.9s

input_handler.cc(94): Throw in function void 
kat::InputHandler::validateMerLen(uint16_t)
Dynamic exception type: 
boost::exception_detail::clone_impl<kat::JellyfishException>
std::exception::what: std::exception
[kat::JellyfishError*] = Cannot process hashes that were created with 
different K-mer lengths.  Expected: 27.  Key length was 0 for : 
/pica/v3/b2011228_nobackup/Debaryomyces_automated/03_Assembly/P1260_1001/soapdenovo_67_assembly/soapdenovo_67_assembly_graph.scafSeq 


Regards,
Mahesh.

**Comment by maplesond** [comment]
Thanks for raising this.  This clearly shows the problem (the .scafSeq extension).    I'll look into trying to autodetect valid filetypes before processing through jellyfish.  I'll let you know when I have a fix.

**Comment by maplesond** [comment]
Hi Mahesh, this will be fixed in V2.1, which will be released before Christmas.

**Comment by mahesh-panchal** [comment]
Thanks.
