### ISSUE TITLE
Pollution of PATH with "jellyfish" exe

### ISSUE THREAD

**Issue by tseemann** [TGAC/KAT#29]
`make install` adds `jellyfish` into the same `bin` folder as `kat`.

This will cause problems with local `jellyfish` installs.

Please install it in a `libexec` folder and tell `kat` to execute that version **or** rename it to `kat.jellyfish` or something similarly unique and non-clashing.

**Comment by maplesond** [comment]
Agreed.  Actually I don't need the executable or shared libraries for KAT.  I static link to the library in dips so there should be no runtime dependencies.  The only reason that's there is that I haven't modified the jellyfish configure.a file to tell it not to do that by default.

**Comment by maplesond** [comment]
On reflection, I think in this case the best solution is to rename the jellyfish executable and libraries (maybe to something like "jellyfishk").  The reason for this is that if KAT is driven by existing jellyfish hashes then KAT is dependent on the specific jellyfish version to work (other versions may work, but there have been instances with jellyfish V1 where minor version changes results in hashes becoming incompatible with KAT.  Therefore, renaming the executable makes it clear that this version of jellyfish is compatible with KAT, without overriding another jellyfish executable that's already on the PATH.  Would this solution work for you?

**Comment by maplesond** [comment]
I should also point out, that there's no reason to use external jellyfish hashes in V2 (processing straight from FastA/Q is actually faster) but I didn't want to remove the option to do so should the user wish to work this way.

**Comment by maplesond** [comment]
Fixed in V2.0.8.  jellyfish binaries names have been modified to avoid clashes with an existing jellyfish installation.  Feel free to reopen if you have further suggestions.
