### ISSUE TITLE
Compiler warnings about deprecated "auto_ptr" ?

### ISSUE THREAD

**Issue by tseemann** [TGAC/KAT#32]
Is this a BOOST or a KAT problem?

```
/bio/linuxbrew/opt/boost//include/boost/get_pointer.hpp:27:40: warning: 'template<class> class std::auto_ptr' is deprecated [-Wdeprecated-dec
larations]
 template<class T> T * get_pointer(std::auto_ptr<T> const& p)
                                        ^
In file included from /bio/linuxbrew/Cellar/gcc/5.2.0/include/c++/5.2.0/memory:81:0,
                 from /bio/linuxbrew/opt/boost//include/boost/config/no_tr1/memory.hpp:21,
                 from /bio/linuxbrew/opt/boost//include/boost/smart_ptr/shared_ptr.hpp:23,
                 from /bio/linuxbrew/opt/boost//include/boost/shared_ptr.hpp:17,
                 from /bio/linuxbrew/opt/boost//include/boost/exception/get_error_info.hpp:18,
                 from /bio/linuxbrew/opt/boost//include/boost/exception/diagnostic_information.hpp:16,
                 from /bio/linuxbrew/opt/boost//include/boost/exception/all.hpp:15,
                 from kat.cc:28:
/bio/linuxbrew/Cellar/gcc/5.2.0/include/c++/5.2.0/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^
In file included from /bio/linuxbrew/opt/boost//include/boost/bind/mem_fn.hpp:25:0,
                 from /bio/linuxbrew/opt/boost//include/boost/mem_fn.hpp:22,
                 from /bio/linuxbrew/opt/boost//include/boost/function/detail/prologue.hpp:18,
                 from /bio/linuxbrew/opt/boost//include/boost/function.hpp:24,
                 from /bio/linuxbrew/opt/boost//include/boost/algorithm/string/detail/find_iterator.hpp:18,
                 from /bio/linuxbrew/opt/boost//include/boost/algorithm/string/find_iterator.hpp:24,
                 from /bio/linuxbrew/opt/boost//include/boost/algorithm/string/iter_find.hpp:27,
                 from /bio/linuxbrew/opt/boost//include/boost/algorithm/string/split.hpp:16,
                 from /bio/linuxbrew/opt/boost//include/boost/algorithm/string.hpp:23,
                 from sect.cc:39:
/bio/linuxbrew/opt/boost//include/boost/get_pointer.hpp:27:40: warning: 'template<class> class std::auto_ptr' is deprecated [-Wdeprecated-declarations]
 template<class T> T * get_pointer(std::auto_ptr<T> const& p)
                                        ^
In file included from /bio/linuxbrew/Cellar/gcc/5.2.0/include/c++/5.2.0/memory:81:0,
                 from sect.cc:23:
/bio/linuxbrew/Cellar/gcc/5.2.0/include/c++/5.2.0/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^
```

**Comment by maplesond** [comment]
Good question.  I'll have to take a look into this.  It looks like a boost problem, I guess there have been some changes in recently, which treat `auto_ptr` as warnings.  (See here: http://stackoverflow.com/questions/2404115/is-auto-ptr-deprecated)  I don't use `auto_ptr` directly in KAT, although I do use the `auto` keyword, mainly for type detection in for loops, which is still very much supported.  

I'll think about this during the week and see if there is anyway to bypass the issue.  Out of interest, which version of boost are you using?  Just wondering if this is a problem in the latest version?

**Comment by zhiliangc** [comment]
I used boost 1.58 and 1.59, they both have the same problem as @tseemann mentioned above

**Comment by maplesond** [comment]
From my understanding of what's going on here it seems like the best we can do is to supress the warnings.  `auto_ptr` is deprecated in C++11 but boost still needs to use them in order to come up with its own implementation of smart pointers (now available in C++11).  Boost needs them for pre C++11 projects that wish to use smart pointers.  I'll continue to read about this but at the moment it seems like it's something we need to live with as I can't easily replace boost in KAT.

**Comment by maplesond** [comment]
There is also some use of auto_ptr in jellyfish:

```
sub_commands/count_main.cc: In function ‘int count_main(int, char**)’:
sub_commands/count_main.cc:248:8: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
   std::auto_ptr<jellyfish::dumper_t<mer_array> > dumper;
        ^
In file included from /usr/include/c++/5/memory:81:0,
                 from sub_commands/count_main.cc:28:
/usr/include/c++/5/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^
```

These warnings only seem to appear when using GCC/G++ 5.  No issues with GCC/G++ V4.8 or V4.9.  I could work around this one I would prefer to avoid making large changes to the jellyfish code base.  An alternative approach could also suppress these warning by putting -Wno-deprecated-declarations but generally would prefer to know about these issues than not, so I'll leave it as is for now.

**Comment by maplesond** [comment]
I'm not aware of any issues related to these warnings so I've added  "-Wno-deprecated-declarations" to kat_jellyfish and to KAT to suppress the warnings messages.  Changes in head of develop branch, will be in V2.1

**Comment by maplesond** [comment]
Changes should be in the current release.  Closing.
