### ISSUE TITLE
Don't install jellyfish include / man pages?

### ISSUE THREAD

**Issue by tseemann** [TGAC/KAT#35]
`make install` on kat seems to also install the jellyfish man and include folders.

These cause clashes with existing jellyfish installs.

Is there a way to not use the bundled jellyfish?

**Comment by maplesond** [comment]
I'll rename the manuals to katjellyfish for V2.1, as in  https://github.com/TGAC/KAT/issues/33

**Comment by maplesond** [comment]
Fixed in head of develop branch, will be in V2.1

**Comment by maplesond** [comment]
Should be fixed in the latest release: https://github.com/TGAC/KAT/releases/tag/Release-2.1.0.  Please reopen if there are any issues.
