### ISSUE TITLE
SMall typo in error message

### ISSUE THREAD

**Issue by jonathandmoore** [TGAC/KAT#42]
Error: Either --list of --intersection must be given.

I think this should say 'or' rather than 'of'.

This is in kat 2.1.0 beta2  (kat plot spectra-mx)

**Comment by maplesond** [comment]
Thanks Jonathan.  I'll make sure this is fixed in the official release.

**Comment by maplesond** [comment]
Should be fixed in the latest release: https://github.com/TGAC/KAT/releases/tag/Release-2.1.0.  Please reopen if there are any issues.
