### ISSUE TITLE
Compiling jellyfish fails with clang: error: variable length array of non-POD element type 'std::__1::thread'

### ISSUE THREAD

**Issue by sjackman** [TGAC/KAT#44]
The workaround is to compile with GCC, but it would be nice to be able to compile with clang. Is it possible to disable compiling `jellyfish` and instead used the copy of `jellyfish` that I already have installed, possibly with a `--with-jellyfish` option?

Here's the failed build log:
https://gist.github.com/sjackman/9515296cd62592ad05c3a637e23e8dc9#file-02-make-L85

```
clang++ -DHAVE_CONFIG_H -I. -I..  -DCPLUSPLUS -I../deps/seqan-library-2.0.0/include -I../deps/jellyfish-2.2.0/include -I../deps/jellyfish-2.2.0/include -I/usr/local/Cellar/boost/1.60.0_1/include  -g -O3 -Wno-conversion-null -Wno-unused-result -Wno-unused-function -Wno-sign-compare -Wnon-virtual-dtor -std=c++11 -DCPLUSPLUS -g -O2 -std=gnu++11 -c -o kat-plot_spectra_cn.o `test -f 'plot_spectra_cn.cc' || echo './'`plot_spectra_cn.cc
jellyfish_helper.cc:232:13: error: variable length array of non-POD element type 'std::__1::thread'
    thread t[threads];
            ^
1 error generated.
make[1]: *** [kat-jellyfish_helper.o] Error 1
```

**Comment by sjackman** [comment]
I believe this bug is fixed in jellyfish 2.2.4

**Comment by maplesond** [comment]
This is actually an issue in the KAT code which I've already fixed in the develop branch af665d0ef93cf6273211754c99acd189232f6d4f.  I will be releasing a new version of KAT soon which will contain this fix.

**Comment by sjackman** [comment]
Wonderful. Please do.

**Comment by maplesond** [comment]
Should be fixed in the latest release: https://github.com/TGAC/KAT/releases/tag/Release-2.1.0.  Please reopen if there are any issues.

**Comment by sjackman** [comment]
Great! Will you open a PR to update the Homebrew-Science `kat` formula?

**Comment by maplesond** [comment]
I'm looking into this today.  I'm running into a bug though when I only seem to encounter when running kat via homebrew.  Possibly something to do with utf8 parsing of command line options? I'll have to try and fix this first.



Sent from my Samsung Galaxy smartphone.


-------- Original message --------
