### ISSUE TITLE
Compiling jellyfish fails with GCC 5: error: 'gettimeofday' was not declared in this scope

### ISSUE THREAD

**Issue by sjackman** [TGAC/KAT#45]
It would really help to use a preinstalled copy of `jellyfish`.

Here's a gist of the log files:
https://gist.github.com/sjackman/1e2a90554a8e2248a7a6ef1cf3192b6b#file-02-make-L97
```
g++-5 -DHAVE_CONFIG_H -I. -I..  -DCPLUSPLUS -I../deps/seqan-library-2.0.0/include -I../deps/jellyfish-2.2.0/include -I../deps/jellyfish-2.2.0/include -I/usr/local/Cellar/boost/1.60.0_1/include  -g -O3 -Wno-conversion-null -Wno-unused-result -Wno-unused-function -Wno-sign-compare -Wnon-virtual-dtor -std=c++11 -DCPLUSPLUS -g -O2 -std=gnu++11 -c -o kat-kat.o `test -f 'kat.cc' || echo './'`kat.cc
In file included from ../deps/jellyfish-2.2.0/include/jellyfish/hash_counter.hpp:23:0,
                 from ./jellyfish_helper.hpp:45,
                 from sect.cc:50:
../deps/jellyfish-2.2.0/include/jellyfish/locks_pthread.hpp: In member function 'int jellyfish::locks::pthread::cond::timedwait(time_t)':
../deps/jellyfish-2.2.0/include/jellyfish/locks_pthread.hpp:59:31: error: 'gettimeofday' was not declared in this scope
     gettimeofday(&timeofday, 0);
```

**Comment by tseemann** [comment]
`<time.h>` and `<sys/time.h>` are two different includes

http://stackoverflow.com/questions/20856691/google-test-gtest-cc812-error-gettimeofday-was-not-declared-in-this-scope

**Comment by maplesond** [comment]
Thanks for reporting this.  I've updated the develop branch replacing <time.h> with <sys/time.h> in the gtest code.  I've confirmed it works correctly on linux but will need to get hold of a Mac for further testing.  I'll leave this case open until we have confirmation it works correctly on Mac.

**Comment by sjackman** [comment]
Travis offers CI testing on Mac. https://docs.travis-ci.com/user/osx-ci-environment/

**Comment by maplesond** [comment]
Nice, I didn't realise it offered Mac support now.  I'll take a look at this later in the week.

**Comment by maplesond** [comment]
Should be fixed in the latest release: https://github.com/TGAC/KAT/releases/tag/Release-2.1.0.  Please reopen if there are any issues.
