### ISSUE TITLE
Segmentation fault when showing options

### ISSUE THREAD

**Issue by vatese** [TGAC/KAT#54]
Compiled on centos 6 with gcc 4.8.2, boost 1.60.0, libtool 2.2.6, python 3.5.1 with matplotlib 1.5.1.

I get this:

```
Kmer Analysis Toolkit (KAT) V2.1.1

Usage: kat hist [options] (<input>)+

Create an histogram of k-mer occurrences from the input.

Create an histogram with the number of k-mers having a given count, derived from the input, which can take the form of a single jellyfish hash, or one or more FastA or FastQ files. In bucket 'i' are tallied the k-mers which have a count 'c' satisfying 'low+i*inc <= c < low+(i+1)'. Buckets in the output are labeled by the low end point (low+i).
The last bucket in the output behaves as a catchall: it tallies all k-mers with a count greater or equal to the low end point of this bucket.
This tool is very similar to the "histo" tool in jellyfish itself.  The primary difference being that the output contains metadata that make the histogram easier for the user to plot.

Options:
Segmentation fault (core dumped)
```

It also occurs with previous versions of KAT.

Many thanks

**Comment by maplesond** [comment]
Hi @vatese, 

The error message suggests there is some problem with boost program options.  So I think either there is some issue with boost itself on your environment, or the way it's linked into KAT.

I'll need a bit more information from you.

- Can you give me the exact command line that you used (presumably `kat hist --help`, or something like it)?  Also do you get the same error for the other tools?  
- Can you confirm that boost was compiled using the same compiler as KAT?
- When you built boost did were there static libraries created (i.e. library files with a `.a` extension)?
- Can you type `ldd kat` and show me the current dynamic dependencies for kat on your system?

Thanks,
Dan

**Comment by vatese** [comment]
Build with the new version of boost 1.61.0, making sure both where compiled with gcc 4.8.2.

The options are displaying ok now.

Many thanks!

**Comment by maplesond** [comment]
You're welcome.  Glad it's working now.
