### ISSUE TITLE
configure.ac:8: error: possibly undefined macro: AC_PROG_LIBTOOL

### ISSUE THREAD

**Issue by kumarsaurabh20** [TGAC/KAT#58]
I was trying to compile KAT on a ubuntu distribution (Linux minerva 3.13.0-96-generic #143-Ubuntu SMP Mon Aug 29 20:15:20 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux) and came across the following error:

`ks575:~/software/KAT/KAT$ ./autogen.sh
autoreconf: Entering directory`.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4 ${ACLOCAL_FLAGS}
autoreconf: configure.ac: tracing
autoreconf: configure.ac: adding subdirectory deps/jellyfish-2.2.0 to autoreconf
autoreconf: Entering directory `deps/jellyfish-2.2.0'
autoreconf: running: aclocal --force -I m4
autoreconf: configure.ac: not using Libtool
autoreconf: running: /home2/ISAD/ks575/software/KAT/autoconf-2.69/build/bin/autoconf --force
configure.ac:8: error: possibly undefined macro: AC_PROG_LIBTOOL
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /home2/ISAD/ks575/software/KAT/autoconf-2.69/build/bin/autoconf failed with exit status: 1`

Any idea how to get over it?
Thanks

**Comment by maplesond** [comment]
Hello,

Do you have libtool installed?  You can type "which libtool" at the commandline to check.

Best regards,
Dan

**Comment by maplesond** [comment]
Also, you can bypass the configuration script generation step by downloading the latest release distributable here: https://github.com/TGAC/KAT/releases/download/Release-2.1.1/kat-2.1.1.tar.gz

**Comment by kumarsaurabh20** [comment]
yes it is installed

**Comment by kumarsaurabh20** [comment]
Many thanks for the new link. It worked, however when I run the kat binary, I get the following:

`ks575:~/software/KAT/kat-2.1.1/build/bin$ ./kat
Throw location unknown (consider using BOOST_THROW_EXCEPTION)
Dynamic exception type: boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<std::logic_error> >
std::exception::what: character conversion failed
`
cant understand If I have a faulty Boost installation?

**Comment by maplesond** [comment]
See issue #57 .  This is a puzzle.  I can only reproduce this issue using linuxbrew on my machine, which does use a different boost installation that my current system installation.  When you run configure do you supply the "--with-boost=" option to explicitly specify the boost directory or do you rely on your system installation?  I would suggest downloading the latest boost version and installing to a separate directory, then use the configuration option described above.  You can look into the .travis/install.sh file in the KAT installation to get an idea for how to do this.  If it works please let me know.  I'd like to try and get to the bottom of this problem.

**Comment by kumarsaurabh20** [comment]
Hi Dan,

Installing boost at custom location worked. Now kat also working perfectly (./kat --help/--version)

Many thanks for your replies. 

Kumar

**Comment by maplesond** [comment]
Great.  I'll have to try an figure out what's causing some versions of boost to behave strangely.  Did you get your original version from apt-get?

**Comment by kumarsaurabh20** [comment]
yes

**Comment by maplesond** [comment]
I've tried using the boost from apt-get and it works fine for me.  I'm not fully sure what caused the original problem but I haven't been able to reproduce and seeing as there is a workaround in place, I'm closing this case.

**Comment by gorliver** [comment]
Hi Dan,
I meet the same issue when install the 2.4.1 version. The libtool is installed. I can send you the configure.ac is necessary.
Thank you!
Gorliver

**Comment by vapdrs** [comment]
As a note to future readers, if you don't have `libtool` installed to a system directory, but instead a custom prefix like `~/.local`, you may need to set

```bash
export ACLOCAL_PATH="${HOME}/.local/share/aclocal/"
```

before running `autogen.sh`
