### ISSUE TITLE
Fix release tarballs to contain generated configure script or fix README.md

### ISSUE THREAD

**Issue by mmokrejs** [TGAC/KAT#59]
Hi,
  your README file states the tar.gz tarballs with sources contain configure but it is not true.

  I have to call "autogen.sh ." to create the missing configure script, which is suboptimal for most users.

**Comment by maplesond** [comment]
Hello, I think you must have downloaded the automatically generated github tarball.  Indeed this version won't contain the premade configure script.  Maybe there's a way to turn this feature off to avoid confusion.  I'll look into it later.  The most recen distribuatable can be downloaded here: https://github.com/TGAC/KAT/releases/download/Release-2.1.1/kat-2.1.1.tar.gz

I'll leave this case open until I've had a chance to look into disabling the github tarballs.

**Comment by mmokrejs** [comment]
Hi,
  thank your for quick answers. I fetched https://github.com/TGAC/KAT/archive/Release-2.1.1.tar.gz  .

**Comment by bjclavijo** [comment]
And that solved your problem, right? I've just downloaded the tar form that link and indeed the configure is there. If so, we'll just leave this open till we disable the github tarballs, but considered it solved for you?

**Comment by mmokrejs** [comment]
Sorry for unclear comment. I posted the URL which I downloaded and which provided the files I used for the bug report.

No, I do not see configure in there still (do not worry about the file being renamed to something else by me):

>  $ gzip -dc kat-2.1.1.tar.gz | tar tvf - | grep configure
> -rw-rw-r-- root/root      7794 2016-07-26 19:24 KAT-Release-2.1.1/configure.ac
> -rw-rw-r-- root/root      5662 2016-07-26 19:24 KAT-Release-2.1.1/deps/jellyfish-2.2.0/configure.ac
> $

**Comment by bjclavijo** [comment]
Ok, to clarify: if you use https://github.com/TGAC/KAT/releases/download/Release-2.1.1/kat-2.1.1.tar.gz as Dan suggested, you'll find the configure.

```
[clavijob@N79047 ~]$ tar tzf Downloads/kat-2.1.1.tar.gz|grep -e 'configure$'
kat-2.1.1/deps/jellyfish-2.2.0/configure
kat-2.1.1/configure
```

We'll fix the read to point this out.

**Comment by maplesond** [comment]
Unfortunately, it appears as though there's no easy way to disable the source code bundles from github, so I've updated the README in the develop branch to remind users to download the distributable which has the filename format: `kat-<version>.tar.gz`.

I'm closing this case now.  Feel free to reopen if you have any outstanding comments.
