### ISSUE TITLE
Update README.md to emphasize that a bundled jellyfish-2.2.0 is included

### ISSUE THREAD

**Issue by mmokrejs** [TGAC/KAT#60]
Hi,
  I was surprised that a bundled jellyfish is included in the source tarball. I have jellyfish already installed. Even more surprisingly you say elsewhere it is a "modified" version. I think you should provide a link to the patch with your changes and second, ensure the modified binary is installed under a new name so that it does not overwrite my current, vanilla jellyfish.

**Comment by maplesond** [comment]
This is fine, the KAT version of the modified jellyfish executable, libraries and manual is prefixed with "kat_" so there will be no conflicts with the existing version of jellyfish installed on your system.

**Comment by mmokrejs** [comment]
Still I would prefer to have this included in README.md. Also, I see seqan-2.0.0 is included.

**Comment by bjclavijo** [comment]
Martin, as both libraries have been included in such a way that they don't generate any conflict in the system, their license files are included where appropriate, etc. I think we're fine with this, all try to enhance the read when we have all these details together.

**Comment by mmokrejs** [comment]
> as both libraries have been included in such a way that they don't generate any conflict in the system

But the conflict happens once the binaries use the original jellyfish during execution. I propose the jellyfish is installed under a modified name, like jellyfish_kat. That means the binary, *.a, headers directory name, *.so, *.pc file at least.

**Comment by maplesond** [comment]
I'm not sure I understand.  Everything has already been modified like you suggest... unless I'm missing something...

**Comment by mmokrejs** [comment]
Oh sorry, I answered from top of my head without checking the actual filenames. I should re-read the docs now or just check what the install procedure does.
