### ISSUE TITLE
Paired-end in Filter seq

### ISSUE THREAD

**Issue by JenCabral** [TGAC/KAT#64]
Is there a way to make filter seq work with paired-end data and keep the data paired-end?

**Comment by maplesond** [comment]
Unfortunately currently not.  You'll need to run kat filter seq on both files and then do a subsequent run on both files to ensure the output is properly paired, discarding those reads which are not found in both files.  

This is a relatively simple feature to add into KAT though.  I'll make sure it's in the next version.

**Comment by Takadonet** [comment]
hey @maplesond, I see that you added this functionality into the latest branch. Any plans to release soon?  Also does the new kat filter seq perform as describe above when using paired end?

**Comment by maplesond** [comment]
Yes: https://github.com/TGAC/KAT/releases/download/Release-2.3.0/kat-2.3.0.tar.gz

I'll close the case, although if there are any issues or it doesn't work how you'd expect it to feel free to reopen.
