### ISSUE TITLE
Compilation of gnuplot library fails

### ISSUE THREAD

**Issue by johnomics** [TGAC/KAT#65]
make fails on `src/libkat_2_1_la-gnuplot_i.lo`:

```
make[2]: Entering directory '/home/johnomics/bin/KAT/kat-2.1.1/lib'
  CXX      src/libkat_2_1_la-gnuplot_i.lo
src/gnuplot_i.cc: In destructor 'Gnuplot::~Gnuplot()':
src/gnuplot_i.cc:412:74: error: throw will always call terminate() [-Werror=terminate]
         throw GnuplotException("Problem closing communication to gnuplot");
                                                                          ^
src/gnuplot_i.cc:412:74: note: in C++11 destructors default to noexcept
cc1plus: all warnings being treated as errors
Makefile:538: recipe for target 'src/libkat_2_1_la-gnuplot_i.lo' failed
make[2]: *** [src/libkat_2_1_la-gnuplot_i.lo] Error 1
make[2]: Leaving directory '/home/johnomics/bin/KAT/kat-2.1.1/lib'
Makefile:550: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/johnomics/bin/KAT/kat-2.1.1'
Makefile:442: recipe for target 'all' failed
make: *** [all] Error 2
```

Using gcc version 6.2.1, KAT versions 2.2.0 and 2.1.1. Please could you suggest a fix for this?

**Comment by maplesond** [comment]
I haven't tried compiling KAT with GCC V6 yet, so maybe the problem is linked to that.  Until I get an opportunity to look into this properly, you could try looking to add -Wno-error=terminate as a compiler flag to workaround the issue.

**Comment by johnomics** [comment]
Thanks - this worked:
```
./configure CPPFLAGS='-Wno-error=terminate'
```

**Comment by maplesond** [comment]
Hi John,

It seems that this is a new warning in GCC6 and I am treating all warnings as errors in the KAT library: https://gnu.wildebeest.org/blog/mjw/2016/02/15/looking-forward-to-gcc6-many-new-warnings/

To be honest, I shouldn't have been throwing an exception from a destructor anyway, so in the next version I'll replace that throw with an error message instead.

Thanks for the heads up.

Dan
