### ISSUE TITLE
One pass filter seq on multiple fasta file

### ISSUE THREAD

**Issue by Takadonet** [TGAC/KAT#66]
Our lab is trying to determine which plasmid sequences to filter in or out for more time consuming down stream analyses based on the filter seq command. 

If we pass our multiple fasta file with all the sequences, it treats as a single filter target. If we split our fasta file up, we are suddenly running filter seq thousand of times on the same input fastq files. Is it possible to either add another column in --stats that indicate which target it in the multiple fasta file?

**Comment by maplesond** [comment]
I think I'll need to understand this request in a bit more detail.  So if I understand you correctly, you've already identified kmers associated with plasmids using the 'filter kmer' tool.  Then using this and a database of plasmids in a fasta file you want to identify those which are covered by a proportion of kmers from your input?  If I've got that correct, I think the stats files already gives the header for each sequence and the statistics associated with it.  So I must be misunderstanding something.  

An alternative approach could be to use the SECT tool.  This can identify statistics regarding kmer counts, median coverage and GC content across sequences.  Maybe you could use this information to get the information you need.  This approach wouldn't extract the sequences from the fasta however.

**Comment by Takadonet** [comment]
I will give that a try first. Our goal is to identify which plasmids are worth pursuing with reference mapping. We have over 3200 targets and really want to reduce to a manageable number in an automated fashion

**Comment by Takadonet** [comment]
Looks like SECT tool is 100% what I want in the first place.
Thanks for the info!
