### ISSUE TITLE
Counting very large k-mers

### ISSUE THREAD

**Issue by dbrowneup** [TGAC/KAT#71]
Hello,

I've been using KAT to count 1000-mers in some of my genome assemblies recently and it works very nicely. However, when I try to count 5000-mers or 10000-mers, `kat hist` gets hung up and just won't finish. I have let it run for 200 hours and still it doesn't progress. It allocates the memory on the system and appears to start counting... no errors occur, it just doesn't finish. Is there an upper limit in the kmer size? Do I need to compile the program differently? Or perhaps is there something I could do to debug more extensively?

Thanks,
Dan

**Comment by maplesond** [comment]
Hi Dan,

To be honest this is something I havent tried before.  I think the largest k value Ive used before is around 250 so you are working in uncharted terratory.  In general I can imagine there being huge memory issues when using such a large k value but it would depend on what genomes you are running on.

Ill run a few experiements in the new year to see whether this kind of use case is feasible.



Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by dbrowneup** [comment]
Thanks for the quick response Daniel. The genome I'm working on is ~166
Mbp. When counting 1000mers it only takes about 70 GB of memory. I use a
hash size of 170 M elements. I specified the same hash size for the
5000mers and 10000mers and the memory requirements are ~400 GB and ~700 GB
respectively. But I've got 2 TB of RAM to play with so thats not a problem.
Let me know if I can do anything to help the debug process!

**Comment by maplesond** [comment]
Hi Dan

The other thing that could be an issue is the minimum length of your contigs. You wont be able to count 5000mers on a 1000bp contig.

Can you check this out in your assembly and see if that might explain the issue?

Cheers,
Dan



Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by dbrowneup** [comment]
The minimum sequence length was 26,202 bp in my last attempts at counting 5000- and 10000-mers. Nonetheless, both attempts got hung up. Counting 1000-mers takes no time at all though:
```
Kmer Analysis Toolkit (KAT) V2.1.1

Running KAT in HIST mode
------------------------

Input is a sequence file.  Counting kmers for B_ABv5-3.fa... done.  Time taken: 17.4s

Bining kmers ... done.  Time taken: 2.2s

Dumping hash to kat_hist_AB-hash.jf1000 ... done.  Time taken: 58.9s

Merging counts ... done.  Time taken: 0.0s

Saving results to disk ... done.  Time taken: 0.0s

Creating plot ... done.  Time taken: 0.3s

KAT HIST completed.
Total runtime: 79.3s


------------------------------------------------------------
Sender: LSF System <lsfadmin@lrg1024-0302>
Subject: Job 3639368: <HIST_AB> in cluster <Main_Compute> Done

Job <HIST_AB> was submitted from host <login5> by user <dbrowne> in cluster <Main_Compute>.
Job was executed on host(s) <40*lrg1024-0302>, in queue <xlarge>, as user <dbrowne> in cluster <Main_Compute>.
</home/dbrowne> was used as the home directory.
</scratch/user/dbrowne/2016.12_DEC/2016.12.16_B_D3AB_K1000/> was used as the working directory.
Started at Sat Dec 17 00:18:32 2016
Results reported on Sat Dec 17 00:20:11 2016

Your job looked like:

------------------------------------------------------------
# LSBATCH: User input
ml Westmere; ml KAT; kat hist -d -t 40 -H 165000000 -m 1000 -o kat_hist_AB B_ABv5-3.fa
------------------------------------------------------------

Successfully completed.

Resource usage summary:

    CPU time :                                   1210.80 sec.
    Max Memory :                                 65050 MB
    Average Memory :                             49783.00 MB
    Total Requested Memory :                     800000.00 MB
    Delta Memory :                               734950.00 MB
    Max Processes :                              6
    Max Threads :                                44

The output (if any) is above this job summary.
```

**Comment by maplesond** [comment]
I get the same kind of behaviour you are described when running jellyfish directly.  It seems that there is some issue when the mer-size becomes larger than a thousand which causes a larger than expected memory spike.  Unfortunately, I can't make address this directly in KAT as it will likely involve significant changes to the internal jellyfish dependency.  I'll raise a ticket with the jellyfish author to see if there's anything that can be done about this, and if so I'll integrate the changes back into KAT.  However, I suspect that this might be something that can't easily be addressed so I wouldn't expect a solution in the short term.

Out of interest, can you tell me why you would like to use such large values for kmers?  Would a smaller k value not be sufficient?

**Comment by maplesond** [comment]
See jellyfish ticket: https://github.com/gmarcais/Jellyfish/issues/79

**Comment by dbrowneup** [comment]
I got interested in analyzing large kmers because I was wondering: how large must I set k for all kmers in the genome to be unique? Turns out there are a substantial number of repeated 1000-mers in the genome that I'm studying, as well as in other genomes I've tested. Since 1000 was not a large enough value for k such that all kmers would be unique, I want to try 5000 and 10000 to see if that will do the trick.

I also think this raises some interesting implications and possibilities for genome assembly algorithms.

**Comment by bjclavijo** [comment]
Just remember there is a big chance all those kmers are coming from a
smallish number of places. As an example, a 3kbp perfect repeat will give
you 2000 repeated 1001-mers. Also, some of this may be assembly artifacts,
for obvious reasons.

You probably should just do a self-alignment of the genome to itself
without using large seeds without a high-frequency filter. Then take the
perfect matches. Then you'll know all of this ;)

Still, using kat is more of a fun!

**Comment by dbrowneup** [comment]
Bernardo, thanks for the comments. I completely agree about the sources of the highly repetitive 1000-mers being perfectly repeated sequences in the genome. Though I do also consider assembly artifacts a possibility. I haven't done it yet, but I intend to BLAST these 1000-mers against NCBI to see if there's any known sequences that are similar. Might also try some other repeat-specific sequence databases.

I really like your idea of doing a self-alignment of the genome, but I'm not sure how to do that. Do you have any suggestions for programs that I could use to achieve that? Alternatively, I have thought about calculating k-mer coverage at each base in the genome and then extracting regions above a certain threshold into a BED file, or something along those lines. I think it would be nice if I could visualize such regions in IGV.

**Comment by maplesond** [comment]
I'm going to close this ticket as supporting K-mers of this size is not going to be supported in KAT 2 at least.  We will consider this in future developments.
