### ISSUE TITLE
`boost::program_options::options_description::options_description

### ISSUE THREAD

**Issue by zhoujiayi** [TGAC/KAT#74]
Hi,
When I running make ,I get the error that "undefined reference to `boost::program_options::options_description::options_description(std::string const&, unsigned int, unsigned int)''"
Thanks.

**Comment by maplesond** [comment]
Sounds like you dont have a static version of the boost program options module on your system.  Two solutions... either use the latest version 2.3.1.  Hopefully that should work.  If not let me know.  Or option 2, ensure the static version of boost program options is available.



Sent from my Samsung Galaxy smartphone.


-------- Original message --------
