### ISSUE TITLE
Extract /dump kmers with particular counts from kat comp

### ISSUE THREAD

**Issue by georgek** [TGAC/KAT#75]
It would be useful to inspect the kmers that appear in certain rows/columns of the kat comp matrix. For example, one might check which kmers are appearing in the assembly that were not present in the reads.

**Comment by MrKevinDC** [comment]
I was interested in a feature similar to this. I would like to be able to extract all the k-mer sequences that  have a 2x multiplicity according to the k-mer comparison plot. Is there currently any way to do this?

I have tried making use of the .mx file and the jellyfish dumps but cant figure out how they are related.

**Comment by bjclavijo** [comment]
We are not planning to add this feature, this should be done with jellyfish or any other k-mer counter of choice.
