### ISSUE TITLE
Detailed documentation on output files

### ISSUE THREAD

**Issue by Takadonet** [TGAC/KAT#79]
I have several end users that have been searching for nice detailed documentation on the different output files from KAT tools, specific KAT SECT.  My ability to explain is limited to what my best guess is for each individual column.

If there is no documentation to reference, have a few questions then...

What do you consider as "invalid_bases" ? Noticed so far that if they are lower case, it will count them as invalid. Our iupac base pair invalid? i.e R,Y, etc..

What does column "%_non_zero_corrected" indicate?

**Comment by maplesond** [comment]
Yes, I should describe the output in the documentation in more detail.  I'll leave this ticket open as a reminder to do that.

So first of all I should say that in the header line the word "bases" should be replaced with "kmers".

"invalid_bases" means number of kmers not recognised by jellyfish as suitable for building a kmer.  This will be anything that is not an A,T,G,C, so yes iupac base pairs would be considered invalid.  Hadn't really considered about lower case character indicating masking.  I should probably look into that.  Again, I'll use this ticket as a reminder.

"%_non_zero_corrected" means the ratio of non-zero kmers to valid kmers within the sequence.  So nb_non_zero kmers / nb_valid_kmers.

Hope that helps.

**Comment by Takadonet** [comment]
Thanks for the extra info. 
One last question, we have been using kat sect for quick present/absent of small regions between 55 to 2k base pairs region and noticed that we  get 100% for column "%_non_zero" but column "non_zero_bases" does not match the full length of the target.  Is this normal?

IE:

seq_name	median	mean	gc%	seq_length	invalid_bases	%_invalid	non_zero_bases	%_non_zero	%_non_zero_corrected
target	85	85.61500	0.49139	**1626**	0	0.00000	**1600**	**100.00000**	100.00000

**Comment by maplesond** [comment]
Yes that sounds right.  Remember "non_zero_bases" should read "non_zero_kmers".  With a kmer size of 27 you would expect seq_length - 27 + 1 kmers in your sequence.

**Comment by Takadonet** [comment]
That is what I thought. So all the missing 26 base pairs in the case would always be the end of the target?

**Comment by maplesond** [comment]
Right.  Another way of looking at it is the last K-mer will start 27bp upstream of the last base.

**Comment by Takadonet** [comment]
So weird thought... since my target is small, 1626 bps, I could reverse complement it and run it again. If it comes up 100% again... would that indicate its a perfect match?

**Comment by maplesond** [comment]
It should be a perfect match anyway.  Assuming you haven't counted K-mers with the canonical option turned off (-N).

**Comment by maplesond** [comment]
I've just pushed some changes that try to deal with all the issues here to the develop branch.  Updated docs, changed header in the SECT stats output and allowing lowercase bases to be considered "valid" in SECT.  I haven't fully tested everything yet and it might be a little while before I create a new release but maybe it helps you out in the meantime.

**Comment by maplesond** [comment]
Actually... with regards to my point about canonical K-mers... even if you did have the -N option switched on you have still got a 100% match, so yes SECT is telling you your sequence is fully covered.

**Comment by Takadonet** [comment]
So if its 100% match, the output does not easily reflect that. My end users are interpreting the output that not perfect match.  

Just a side note that we really like KAT and hope to incorporate in many different applications.

**Comment by maplesond** [comment]
Hmm, maybe to clarify I should add a column listing the number of K-mers, as represented by a sliding window of size K, are to be analysed in the target sequence?  In your example, that number would be 1600, and because you have a non-zero count at each window (i.e. 1600), and no invalid kmers then you get 100% in the last two columns.

**Comment by maplesond** [comment]
BTW, it's great that you are finding KAT useful! :)  Thanks for the feedback.

**Comment by Takadonet** [comment]
That would clarify it I think. So people will see that all k-mers generated from the target were found matches.

**Comment by maplesond** [comment]
The changes are in the latest version v2.3.3.  Closing case.  Feel free to reopen if there are any further issues.
