### ISSUE TITLE
Problems with version 2.3.1

### ISSUE THREAD

**Issue by jerowe** [TGAC/KAT#83]
We are getting this error with 2.3.1, but not 2.0.8. Both are from the bioconda packages.

```
            ../deps/seqan-library-2.0.0/include/seqan/basic/basic_exception.h:368../deps/seqan-library-2.0.0/include/seqan/basic/basic_exception.h:368 FAILED!  ( FAILED!  (Uncaught exception of type boost::exception_detail::clone_impl<kat::JellyfishException>: std::exception)
```

**Comment by maplesond** [comment]
Hi @jerowe ,
Sorry for not getting back to you on this sooner.  Do you have an example file that triggers this error?  If so I can try to come up with a fix or a workaround for you.

**Comment by maplesond** [comment]
Should be fixed in latest release and via bioconda channel.
