### ISSUE TITLE
Suggestion for increasing scalability

### ISSUE THREAD

**Issue by mahesh-panchal** [TGAC/KAT#86]
Hi, 

I love using KAT for QC, but it doesn't scale well to large genomes.
Would it be possible to use a similar approach to https://github.com/bcgsc/ntCard for making comparisons and breaking down k-mers in much much larger datasets?

Regards,
Mahesh.

**Comment by maplesond** [comment]
Hi Mahesh,
This is something we've been considering for a while.  It will be in a future release but currently I can't put a timeline on that.
Best regards,
Dan

**Comment by maplesond** [comment]
This will not be done in KAT 2, so I'm closing this case.  @bjclavijo may look into this for V3.
