### ISSUE TITLE
kat plot spectra-mx: python error

### ISSUE THREAD

**Issue by fwhelan** [TGAC/KAT#90]
Thank you so much for creating such a great tool! I've been using `kat comp` and various parts of `kat plot` without issue until I recently tried `kat plot spectra-mx`:

```
$ kat plot spectra-mx
Kmer Analysis Toolkit (KAT) V2.4.0

Traceback (most recent call last):
  File "/home/whelanfj/.linuxbrew/Cellar/kat/2.4.0/lib/python3.6/local/kat/plot/spectra_mx.py", line 224, in <module>
    main()
  File "/home/whelanfj/.linuxbrew/Cellar/kat/2.4.0/lib/python3.6/local/kat/plot/spectra_mx.py", line 17, in main
    parser.add_argument("matrix_file", type=str,
UnboundLocalError: local variable 'str' referenced before assignment
../lib/include/kat/pyhelper.hpp(159): Throw in function void kat::PyHelper::execute(std::__cxx11::string, int, char**)
Dynamic exception type: boost::exception_detail::clone_impl<kat::KatPythonException>
std::exception::what: std::exception
[kat::KatPythonError*] = Unexpected python error
```

I installed via brew (`brew install brewsci/bio/kat`) and don't have any issues with any of the other `kat plot` options.

Thanks for your help!
--Fiona

**Comment by maplesond** [comment]
Hi @fwhelan,  I'm glad you like using KAT! :)
Many thanks for the heads up here.  I can reproduce the problem and will issue a patch as soon as possible. 
Best regards,
Dan

**Comment by fwhelan** [comment]
Thanks very much, Dan!

**Comment by maplesond** [comment]
No problem.  I've already fixed this on the develop branch, so if you don't mind building from source you could try that.  Otherwise it will take a few days / weeks to issue a new release and get it updated on brew and bioconda.

**Comment by fwhelan** [comment]
Nope, I'm dumb. I just installed from the develop branch and it worked perfectly. Thank you so much, Dan!

From my perspective, this issue is closed but I'll let you manage whether you want this open for the brew aspect of things.

Cheers,
Fiona

**Comment by maplesond** [comment]
No problem.  Glad it's all working for you.  I'll keep the ticket open until the next release is out.  Thanks for reporting the issue.

**Comment by maplesond** [comment]
Hi @fwhelan, I've made an official release now so I'll close this case now.  I've also put in pull requests to bioconda and brew so KAT should be available via those channels in the coming days.
