### ISSUE TITLE
Upgrade bundled jellyfish to avoid python name conflict

### ISSUE THREAD

**Issue by mmokrejs** [TGAC/KAT#96]
Hi,
  this is a blind shot as there are probably always bugs fixed in a new release but provided KAT bundles at the moment 2.2.6 version: there is https://github.com/gmarcais/Jellyfish/issues/69 which you may want to learn more about

  Or try to really send upstream your changes? Or how about keeping a KAT-specific patch along KAT distribution and patching current version of jellyfish during building?

**Comment by maplesond** [comment]
I don't think this is an issue in KAT.  I've removed all swig bindings from jellyfish, so there should be no possibility of python name clashes.  Is there something I've missed here?

**Comment by mmokrejs** [comment]
I did not even bother to check in more detail what is or is not in the budled coppy. I just wanted to make you aware of this. Sorry, seems irrelevant then.
