### ISSUE TITLE
Make it clear what output files will be created

### ISSUE THREAD

**Issue by mmokrejs** [TGAC/KAT#99]
Hi,
  it is difficult for me to guess what files kat will output during whatever step. In shell scripts which I run repeatedly I want to wrap the calls to kat with an `if` condition checking whether the output file is already present. In such case, I want to skip the call.

  The generated docs and runtime help texts talk about output prefixes at the best, but that is not enough. Now as I have some output files can craft the `if` conditionals but nevertheless, you may want to improve the docs.

   Further, a fat warning could be output for `kat gcp` due to output file sizes:

```
-rw-rw----  1 mmokrejs mmokrejs 113K Apr 30 02:54 gcp__both_PE_datasets.mx
-rw-rw----  1 mmokrejs mmokrejs  96G Apr 30 02:54 gcp__both_PE_datasets-hash.jf27
```

  The output files from other tools (I tried so far) output small files. It is good to know in advance. Same the memory requirements. Seems something took about 110GB of RAM in the series of commands I tried overnight.

**Comment by maplesond** [comment]
So in normal usage I wouldn't recommend emmiting the jellyfish hash file to disk `-d`.  1. as you can see it can be really large for one and storage is normally at a premium.  2. It's actually slower loading a hash into memory, than the fastqs, when multi-threading.  So use at least 4 threads, and you should be substantially faster loading fastqs (particularly if they are gzipped).  110GB of RAM is not completely unexpected.  It depends on how many distinct kmers you have in your dataset.

**Comment by mmokrejs** [comment]
> So in normal usage I wouldn't recommend emmiting the jellyfish hash file to disk -d

Well I wasn't knowing what I am doing, the docs were too short for me so I studied the runtime help options and selected some which seemed reasonable. Maybe add a note to the runtime help text?

BTW, can the vary same `kat` command be ru-run so that it would create/update the output figures if they are missing or input files changed timestamps?

**Comment by maplesond** [comment]
If you rerun the same command it will do exactly the same thing.  There's no intelligence built in to not do work if timestamps haven't changed.

**Comment by mmokrejs** [comment]
> If you rerun the same command it will do exactly the same thing. There's no intelligence built in to not do work if timestamps haven't changed.

For computation-heavy steps I would certainly recommend that. You can expose `--overwrite` option so the timestamp could be ignored. As you know I have precomputed data and just want to re-draw figures.

**Comment by maplesond** [comment]
So the figures only need the .mx or .hist files to be present.  These are normally really small.  And you can use the `kat plot` tools to redraw directly from these files.

**Comment by maplesond** [comment]
Hi @mmokrejs,  I've updated some of the wording in the help and documentation to clarify a few things: d5b6ceaa67ce960c423e2530bdae9a59383571f2 and d18aafd11d282f7d47e9eb5266d48a57a2a99409

Unfortunately, I won't have time for an extensive overhaul of the documentation.  If there are any other specific tweaks you want me to make let me know otherwise I'll close the case.
